// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvz1JXfcmThUl6p-zLfK_3Gnwoj6LqFk',
    appId: '1:582611485464:web:8b0eb745f1669aa8ff946d',
    messagingSenderId: '582611485464',
    projectId: 'chatapp-848b6',
    authDomain: 'chatapp-848b6.firebaseapp.com',
    storageBucket: 'chatapp-848b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdneLHjbmGGE6PREPnaJK3OMfSzHC6hiQ',
    appId: '1:582611485464:android:e2607699e2687600ff946d',
    messagingSenderId: '582611485464',
    projectId: 'chatapp-848b6',
    storageBucket: 'chatapp-848b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdFs2cFiywpm1AfUwPZBAo-ILpt1EE5nI',
    appId: '1:582611485464:ios:b2b6b7b7fd09d8d9ff946d',
    messagingSenderId: '582611485464',
    projectId: 'chatapp-848b6',
    storageBucket: 'chatapp-848b6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdFs2cFiywpm1AfUwPZBAo-ILpt1EE5nI',
    appId: '1:582611485464:ios:b2b6b7b7fd09d8d9ff946d',
    messagingSenderId: '582611485464',
    projectId: 'chatapp-848b6',
    storageBucket: 'chatapp-848b6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmvz1JXfcmThUl6p-zLfK_3Gnwoj6LqFk',
    appId: '1:582611485464:web:9f60f7303a4cfa94ff946d',
    messagingSenderId: '582611485464',
    projectId: 'chatapp-848b6',
    authDomain: 'chatapp-848b6.firebaseapp.com',
    storageBucket: 'chatapp-848b6.firebasestorage.app',
  );
}
